services:
  frontend:
    container_name: mengkocak-app-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://mengkocak-app-backend:3000/
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/frontend
      - /frontend/.next
      - /frontend/node_modules

  backend:
    container_name: mengkocak-app-backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@mengkocak-app-postgres:5432/mengkocak
      JWT_TOKEN: dev_token # only a temporary value for development
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  db:
    image: postgres:14
    container_name: mengkocak-app-postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mengkocak
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
